[build]
  command = "npm run build"
  publish = ".next/standalone"
  functions = "functions"

[[plugins]]
package = "@netlify/plugin-nextjs"
  [plugins.inputs]
  publish = ".next"

[functions]
  directory = "functions"