[build]
  command = "npm run build"
  publish = ".next"
  functions = "functions"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[functions]
  directory = "functions"
  included_files = ["!.eslintrc.js", "!.eslintrc.json", "!package.json", "!*.md"]